services:
  squeezelite-dx5:
    build: .
    container_name: squeezelite-dx5
    network_mode: host
    #user: "1000:1000" # Matches your host user ID
    volumes:
      # Map the PipeWire socket from your host into the container
      - /run/user/1000/pipewire-0:/tmp/pipewire-0
      - /dev/shm:/dev/shm
    environment:
      - PLAYER_NAME=DX5 # part of name like in wpctl status Audio - to set volume
      - SERVER_IP=192.168.111.111:3483
      - MAC_ADDR=72:23:90:88:38:63
      # Tell the PipeWire library inside the container where to find the socket
      - PIPEWIRE_RUNTIME_DIR=/tmp
      - PIPEWIRE_REMOTE=pipewire-0
      # Target your DX5 specifically
      - PIPEWIRE_NODE=alsa_output.usb-Topping_DX5-00.analog-stereo # like sync name in wpctl status
      - SQUEEZE_EXTRA=-a 16384:8:24:0 -b 8000:12000 -D 500
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 95
      memlock: -1
    group_add:
      - audio
    restart: unless-stopped